USE [RofDatamart];
GO

IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'JobExecutionHistory'))
BEGIN
	DROP TABLE dbo.JobExecutionHistory;
END

CREATE TABLE dbo.JobExecutionHistory
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	JobType VARCHAR(25) NOT NULL,
	LastDatePulled DATE NOT NULL
);