CREATE TABLE dbo.Employee(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Username VARCHAR(32) NOT NULL,
	Password VARBINARY(max) NOT NULL,
	Role VARCHAR(25) NOT NULL,
	FirstLoggedIn BIT DEFAULT 0 NOT NULL,
	Active BIT DEFAULT 1 NOT NULL
);