IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Vaccines'))
BEGIN
	DROP TABLE dbo.Vaccines;
END

CREATE TABLE dbo.Vaccines(
	Id SMALLINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PetTypeId SMALLINT NOT NULL FOREIGN KEY REFERENCES dbo.PetType(Id),
	VaxName VARCHAR(50) NOT NULL
);