IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PetType'))
BEGIN
	DROP TABLE dbo.PetType;
END

CREATE TABLE dbo.PetType(
	Id SMALLINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PetTypeName VARCHAR(50) NOT NULL
);