IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Client'))
BEGIN
	DROP TABLE dbo.Client;
END

CREATE TABLE dbo.Client(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CountryId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Country(Id),
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	EmailAddress VARCHAR(50) NOT NULL,
	Username VARCHAR(32) NOT NULL,
	Password VARBINARY(max) NOT NULL,
	PrimaryPhoneNum VARCHAR(25) NOT NULL,
	SecondaryPhoneNum VARCHAR(25),
	TempPasswordChanged BIT DEFAULT 0 NOT NULL, 
	IsLocked BIT DEFAULT 0 NOT NULL, 
	FailedLoginAttempts SMALLINT DEFAULT 0 NOT NULL,
	IsLoggedIn BIT DEFAULT 0 NOT NULL,
	AddressLine1 VARCHAR(255) NOT NULL,
	AddressLine2 VARCHAR(50),
	City VARCHAR(50) NOT NULL,
	State VARCHAR(2) NOT NULL,
	ZipCode VARCHAR(10) NOT NULL
);