IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PetToVaccine'))
BEGIN
	DROP TABLE dbo.PetToVaccine;
END

CREATE TABLE dbo.PetToVaccine(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PetId BIGINT FOREIGN KEY REFERENCES dbo.Pet(Id),
	VaxId SMALLINT FOREIGN KEY REFERENCES dbo.Vaccines(Id),
	Inoculated BIT NOT NULL DEFAULT '0'
);