IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Holidays'))
BEGIN
	DROP TABLE dbo.Holidays;
END

CREATE TABLE dbo.Holidays(
	Id SMALLINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HolidayName VARCHAR(55) NOT NULL,
	HolidayMonth SMALLINT NOT NULL,
	HolidayDay SMALLINT NOT NULL,
	CONSTRAINT UC_HolidayName UNIQUE(HolidayName)
);