IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HolidayRates'))
BEGIN
	DROP TABLE dbo.HolidayRates;
END

CREATE TABLE dbo.HolidayRates(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PetServiceId SMALLINT NOT NULL FOREIGN KEY REFERENCES dbo.PetServices(Id),
	HolidayId SMALLINT NOT NULL FOREIGN KEY REFERENCES dbo.Holidays(Id),
	HolidayRate DECIMAL(5, 2) NOT NULL, -- percentage
	CONSTRAINT UC_PetServiceId_HolidayId UNIQUE(PetServiceId, HolidayId)
);