IF (EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Events'))
BEGIN
	DROP TABLE dbo.Events;
END

CREATE TABLE dbo.Events(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	EmployeeId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Employee(Id),
	ClientId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Client(Id),
	PetId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Pet(Id),
	PetServiceId SMALLINT NOT NULL FOREIGN KEY REFERENCES dbo.PetServices(Id),
	EventMonth SMALLINT NOT NULL,
	EventDay SMALLINT NOT NULL
);