USE [master]
GO

/****** Object:  Database [RofDatamart]    Script Date: 4/13/2023 7:20:11 PM ******/
CREATE DATABASE [RofDatamart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RofDatamart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RofDatamart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RofDatamart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RofDatamart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RofDatamart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RofDatamart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RofDatamart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RofDatamart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RofDatamart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RofDatamart] SET ARITHABORT OFF 
GO

ALTER DATABASE [RofDatamart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RofDatamart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RofDatamart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RofDatamart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RofDatamart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RofDatamart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RofDatamart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RofDatamart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RofDatamart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RofDatamart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RofDatamart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RofDatamart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RofDatamart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RofDatamart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RofDatamart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RofDatamart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RofDatamart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RofDatamart] SET RECOVERY FULL 
GO

ALTER DATABASE [RofDatamart] SET  MULTI_USER 
GO

ALTER DATABASE [RofDatamart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RofDatamart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RofDatamart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RofDatamart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RofDatamart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RofDatamart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RofDatamart] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RofDatamart] SET  READ_WRITE 
GO


